### ISSUE TITLE
wallet password issue

### ISSUE THREAD

**Issue by 97albertus** [moneropay/moneropay#5] opened 2023-05-30 18:16 UTC
I've set up a docker container following the steps from https://moneropay.eu/guide/install.html

This is the error I get in the moneropay-1 container logs:

2023-05-30 18:05:48.648	    ffff85c25038	INFO	logging	contrib/epee/src/mlog.cpp:273	New log categories: *:WARNING,net:FATAL,net.http:FATAL,net.ssl:FATAL,net.p2p:FATAL,net.cn:FATAL,daemon.rpc:FATAL,global:INFO,verify:FATAL,serialization:FATAL,daemon.rpc.payment:ERROR,stacktrace:INFO,logging:INFO,msgwriter:INFO
2023-05-30 18:05:48.650	    ffff85c25038	INFO	msgwriter	src/common/scoped_message_writer.h:102	This is the RPC monero wallet. It needs to connect to a monero
2023-05-30 18:05:48.651	    ffff85c25038	INFO	msgwriter	src/common/scoped_message_writer.h:102	daemon to work correctly.
2023-05-30 18:05:48.654	    ffff85c25038	INFO	msgwriter	src/common/scoped_message_writer.h:102	Monero 'Fluorine Fermi' (v0.18.1.2-release)
2023-05-30 18:05:48.658	    ffff85c25038	INFO	msgwriter	src/common/scoped_message_writer.h:102	Logging to monero-wallet-rpc.log
2023-05-30 18:05:48.662	    ffff85c25038	WARNING	wallet.rpc	src/wallet/wallet_rpc_server.cpp:4549	Loading wallet...
2023-05-30 18:05:49.714	    ffff85c25038	ERROR	default	contrib/epee/src/portable_storage.cpp:100	portable_storage: wrong binary format - signature mismatch
2023-05-30 18:05:49.716	    ffff85c25038	ERROR	wallet.wallet2	src/wallet/wallet2.cpp:4480	!r. THROW EXCEPTION: error::invalid_password
2023-05-30 18:05:49.717	    ffff85c25038	INFO	stacktrace	src/common/stack_trace.cpp:133	Exception: tools::error::invalid_password
2023-05-30 18:05:49.717	    ffff85c25038	INFO	stacktrace	src/common/stack_trace.cpp:134	Unwound call stack:

**Comment by 97albertus** [comment] 2023-05-30 18:22
Upd:
chown fixed the aforementioned issue, however now a new issue has occured

```
2023-05-30 23:19:53 Monero 'Fluorine Fermi' (v0.18.1.2-release)
2023-05-30 23:19:53 Logging to monero-wallet-rpc.log
2023-05-30 23:19:53 2023-05-30 18:19:53.657     W Loading wallet...
2023-05-30 23:19:54 2023-05-30 18:19:54.383     E Failed to open wallet_1.keys: Operation not permitted
2023-05-30 23:19:54 2023-05-30 18:19:54.383     E !is_keys_file_locked(). THROW EXCEPTION: error::wallet_internal_error
2023-05-30 23:19:54 2023-05-30 18:19:54.392     E Wallet initialization failed: internal error: "wallet_1.keys" is opened by another wallet program
```

I've ensured that no other wallet is running on my machine, so im not sure what's causing the issue

**Comment by 97albertus** [comment] 2023-05-30 18:36
Upd:
changed read/write perms of file to allow access to everyone, now the wrong password issue is back :/

**Comment by sausagenoods** [comment] 2023-05-31 22:49
Did you create the `wallet.passwd` file or did you remove `--password-file wallet.passwd` from docker-compose.yaml?

**Comment by 97albertus** [comment] 2023-06-10 09:24
sorry for the delay.
Yes, I did create a wallet.passwd file

**Comment by sausagenoods** [comment] 2023-06-10 10:05
Is your password in the file? Or are you passing the password through command line arguments? It isn't a permission issue as the logs in the issue description shows the wallet-rpc-server was able to open and read the wallet. It looks like you're either not supplying the password for the wallet or something is wrong with your wallet file.

Also this one is caused by wrong permissions after you ran chown. This error message isn't very intuitive I know.
https://github.com/moneropay/moneropay/issues/5#issuecomment-1568875422

**Comment by 97albertus** [comment] 2023-06-10 11:34
the thing is I dont have a password on the wallet file, it's blank, so I left the wallet.passwd file blank
I did try running a wallet with a password but the results were the same

I passed the password via .passwd file

**Comment by 97albertus** [comment] 2023-06-10 11:34
I did try running a wallet with a password but the results were the same

**Comment by sausagenoods** [comment] 2023-06-18 12:59
I cannot replicate the errors and also it's not related MoneroPay. So therefore I'm closing this issue now.

We have a [Matrix chat](https://matrix.to/#/#moneropay:kernal.eu) and you might have luck there if you share more information about your setup. We also offer paid commercial support/hosting at https://digilol.net.

**Closed as completed by sausagenoods** 2023-06-18 12:59 UTC
